server:
  port: ${PORT:8080}

app:
  token:
    secret-key: ${JWT_SECRET_KEY:Y3Vyc28tYXV0ZW50aWNhY2FvLXN0YXRlZnVsbC1zdGF0ZWxlc3MtbWljcm9zZXJ2aWNvcw==}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
